server:
  port: 8765

spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          
      routes:
        - id: Authentication-Service
          uri: lb://auth
          predicates:
            - Path=/auth/**

        - id: AI-Chatbot
          uri: lb://chatbot
          predicates:
            - Path=/chatbot/**
          filters:
            - AuthenticationFilter
        
        - id: Doctors-Helpdesk
          uri: lb://helpdesk
          predicates:
            - Path=/helpdesk/**
          filters:
            - AuthenticationFilter

        - id: Covid19-Database-Connection
          uri: lb://coviddata
          predicates:
          - Path=/covidData/**
          filters:
            - AuthenticationFilter

            
      # globalcors:
      #   add-to-simple-url-handler-mapping: true
      #   corsConfigurations:
      #     '[/**]':
      #       allowedOrigins: "http://localhost:5173"
      #       allowedMethods:
      #         - GET
      #         - POST
      #         - PUT
      #         - DELETE
      #         - OPTIONS
      #       allowedHeaders: "*"
      #       allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true